services:
  - type: web
    name: datainsight-backend
    env: node
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: NPM_CONFIG_PRODUCTION
        value: 'false'
